import { ComponentStories } from './types';

export const DEFAULT_STORY_ID = 'hero-banner--default';

export const storiesRegistry: ComponentStories[] = [
  {
    slug: 'hero-banner',
    title: 'Hero Banner',
    description: 'Full-width promotional banner with headline, subtitle and CTA buttons. Supports image overlays and configurable alignment.',
    status: 'READY',
    ownerTeam: 'Marketing Platform',
    aemComponentPath: '/apps/aem-visual-library/components/content/hero-banner',
    aemAllowedChildren: [],
    aemLimitations: [
      'Maximum two CTA buttons per instance',
      'Background video not supported on mobile viewports',
      'Overlay opacity is fixed — cannot be customised per-page',
    ],
    figmaUrl: 'https://www.figma.com/file/example/hero-banner',
    authoringNotes: '<p>Drag and drop the <strong>Hero Banner</strong> component into the page. Use the dialog to set headline, subtitle, CTA labels and target URLs. Choose an overlay colour from the Style tab.</p><ul><li>Keep headlines under 60 characters</li><li>Subtitle is optional — leave blank to hide</li><li>Use the DAM path picker for background images</li></ul>',
    designSpecsNotes: '<p>Min height: <code>420px</code> desktop / <code>280px</code> mobile. Typography: heading is <code>display-2</code>, subtitle is <code>body-lg</code>. Primary CTA uses brand primary fill; secondary uses ghost style.</p>',
    stories: [
      { id: 'default', name: 'Default', description: 'Standard hero with dark overlay', args: { title: 'Experience More with AEM', subtitle: 'Build faster, author smarter.', alignment: 'left', overlay: 'dark', ctaText: 'Get Started', ctaSecondaryText: 'Learn More', bgColor: '#2563eb' } },
      { id: 'centered', name: 'Centered', description: 'Centre-aligned content', args: { title: 'Welcome to Our Platform', subtitle: 'Everything you need in one place.', alignment: 'center', overlay: 'dark', ctaText: 'Explore Now', ctaSecondaryText: '', bgColor: '#7c3aed' } },
      { id: 'no-overlay', name: 'No Overlay', description: 'No background overlay', args: { title: 'Clean & Modern', subtitle: 'Minimal style hero variant.', alignment: 'left', overlay: 'none', ctaText: 'Discover', ctaSecondaryText: 'Watch Video', bgColor: '#059669' } },
      { id: 'dark', name: 'Dark Background', description: 'Dark colour scheme', args: { title: 'The AEM Design System', subtitle: 'Enterprise-grade components.', alignment: 'left', overlay: 'dark', ctaText: 'Get Access', ctaSecondaryText: 'Documentation', bgColor: '#111827' } },
    ],
    controls: [
      { key: 'title', label: 'Title', type: 'text', defaultValue: 'Experience More with AEM' },
      { key: 'subtitle', label: 'Subtitle', type: 'text', defaultValue: 'Build faster, author smarter.' },
      { key: 'alignment', label: 'Alignment', type: 'select', defaultValue: 'left', options: ['left', 'center'] },
      { key: 'overlay', label: 'Overlay', type: 'select', defaultValue: 'dark', options: ['none', 'dark', 'light'] },
      { key: 'ctaText', label: 'Primary CTA', type: 'text', defaultValue: 'Get Started' },
      { key: 'ctaSecondaryText', label: 'Secondary CTA', type: 'text', defaultValue: 'Learn More' },
      { key: 'bgColor', label: 'Background Colour', type: 'color', defaultValue: '#2563eb' },
    ],
  },
  {
    slug: 'cta-button',
    title: 'CTA Button',
    description: 'Configurable call-to-action button with four visual variants and three size options.',
    status: 'READY',
    ownerTeam: 'Core Components',
    aemComponentPath: '/apps/aem-visual-library/components/content/cta-button',
    aemAllowedChildren: [],
    aemLimitations: ['Icon placement limited to left side only'],
    stories: [
      { id: 'default', name: 'Primary', description: 'Default primary button', args: { label: 'Get Started', variant: 'primary', size: 'md', disabled: false } },
      { id: 'secondary', name: 'Secondary', description: 'Secondary / tonal style', args: { label: 'Learn More', variant: 'secondary', size: 'md', disabled: false } },
      { id: 'ghost', name: 'Ghost', description: 'Outline ghost button', args: { label: 'View All', variant: 'ghost', size: 'md', disabled: false } },
      { id: 'disabled', name: 'Disabled', description: 'Disabled state', args: { label: 'Unavailable', variant: 'primary', size: 'md', disabled: true } },
    ],
    controls: [
      { key: 'label', label: 'Label', type: 'text', defaultValue: 'Get Started' },
      { key: 'variant', label: 'Variant', type: 'select', defaultValue: 'primary', options: ['primary', 'secondary', 'ghost', 'link'] },
      { key: 'size', label: 'Size', type: 'select', defaultValue: 'md', options: ['sm', 'md', 'lg'] },
      { key: 'disabled', label: 'Disabled', type: 'boolean', defaultValue: false },
    ],
  },
  {
    slug: 'card',
    title: 'Card',
    description: 'Versatile content card supporting vertical and horizontal layouts with optional image, heading, description and link.',
    status: 'READY',
    ownerTeam: 'Core Components',
    aemComponentPath: '/apps/aem-visual-library/components/content/card',
    aemLimitations: ['Images must be 16:9 or 4:3 ratio for best results'],
    authoringNotes: '<p>Use cards within a <strong>Card Grid</strong> container. Authors can choose vertical or horizontal layout from the Style tab. The CTA link supports both internal page paths and external URLs.</p>',
    stories: [
      { id: 'default', name: 'Default', description: 'Standard vertical card', args: { title: 'Card Heading', description: 'A brief description of this card content.', ctaText: 'Read More', layout: 'vertical', variant: 'default', showImage: true } },
      { id: 'horizontal', name: 'Horizontal', description: 'Side-by-side layout', args: { title: 'Horizontal Card', description: 'Image and text sit side by side.', ctaText: 'Explore', layout: 'horizontal', variant: 'default', showImage: true } },
      { id: 'elevated', name: 'Elevated', description: 'Drop shadow variant', args: { title: 'Elevated Card', description: 'Stronger visual elevation for featured content.', ctaText: 'Learn More', layout: 'vertical', variant: 'elevated', showImage: true } },
      { id: 'no-image', name: 'No Image', description: 'Text-only card', args: { title: 'Text Only Card', description: 'No image, useful for stat or feature cards.', ctaText: 'Details', layout: 'vertical', variant: 'outline', showImage: false } },
    ],
    controls: [
      { key: 'title', label: 'Title', type: 'text', defaultValue: 'Card Heading' },
      { key: 'description', label: 'Description', type: 'text', defaultValue: 'A brief description of this card content.' },
      { key: 'ctaText', label: 'CTA Text', type: 'text', defaultValue: 'Read More' },
      { key: 'layout', label: 'Layout', type: 'select', defaultValue: 'vertical', options: ['vertical', 'horizontal'] },
      { key: 'variant', label: 'Variant', type: 'select', defaultValue: 'default', options: ['default', 'elevated', 'outline'] },
      { key: 'showImage', label: 'Show Image', type: 'boolean', defaultValue: true },
    ],
  },
  {
    slug: 'navigation-header',
    title: 'Navigation Header',
    description: 'Site-wide top navigation bar with logo, nav links, optional search and sticky behaviour.',
    status: 'READY',
    ownerTeam: 'Platform',
    aemComponentPath: '/apps/aem-visual-library/components/structure/navigation-header',
    aemAllowedChildren: ['navigation', 'search'],
    aemLimitations: [
      'Maximum two levels of navigation nesting',
      'Mega-menu requires the Navigation Mega Menu component child',
    ],
    stories: [
      { id: 'default', name: 'Light', description: 'Default light theme', args: { theme: 'light', showSearch: true, sticky: true, logoText: 'My Brand' } },
      { id: 'dark', name: 'Dark', description: 'Dark theme header', args: { theme: 'dark', showSearch: true, sticky: true, logoText: 'My Brand' } },
      { id: 'no-search', name: 'No Search', description: 'Without search icon', args: { theme: 'light', showSearch: false, sticky: false, logoText: 'Acme Corp' } },
    ],
    controls: [
      { key: 'theme', label: 'Theme', type: 'select', defaultValue: 'light', options: ['light', 'dark'] },
      { key: 'showSearch', label: 'Show Search', type: 'boolean', defaultValue: true },
      { key: 'sticky', label: 'Sticky', type: 'boolean', defaultValue: true },
      { key: 'logoText', label: 'Logo Text', type: 'text', defaultValue: 'My Brand' },
    ],
  },
  {
    slug: 'accordion',
    title: 'Accordion',
    description: 'Expandable content panels ideal for FAQs, progressive disclosure and grouped information.',
    status: 'READY',
    ownerTeam: 'Core Components',
    aemComponentPath: '/apps/aem-visual-library/components/content/accordion',
    aemAllowedChildren: ['accordion-item'],
    stories: [
      { id: 'default', name: 'Default', description: 'Single open at a time', args: { allowMultiple: false, theme: 'light', itemTitle: 'What is AEM?' } },
      { id: 'multi', name: 'Multi-expand', description: 'Multiple panels open', args: { allowMultiple: true, theme: 'light', itemTitle: 'What is AEM?' } },
      { id: 'dark', name: 'Dark', description: 'Dark theme variant', args: { allowMultiple: false, theme: 'dark', itemTitle: 'How does it work?' } },
    ],
    controls: [
      { key: 'allowMultiple', label: 'Allow Multiple Open', type: 'boolean', defaultValue: false },
      { key: 'theme', label: 'Theme', type: 'select', defaultValue: 'light', options: ['light', 'dark'] },
      { key: 'itemTitle', label: 'First Item Title', type: 'text', defaultValue: 'What is AEM?' },
    ],
  },
  {
    slug: 'tabs',
    title: 'Tabs',
    description: 'Horizontally or vertically oriented tabbed content panels with configurable active state.',
    status: 'READY',
    ownerTeam: 'Core Components',
    aemComponentPath: '/apps/aem-visual-library/components/content/tabs',
    aemAllowedChildren: ['tab-panel'],
    stories: [
      { id: 'default', name: 'Horizontal', description: 'Standard horizontal tabs', args: { orientation: 'horizontal', theme: 'light', activeTab: 'Overview' } },
      { id: 'vertical', name: 'Vertical', description: 'Side navigation tabs', args: { orientation: 'vertical', theme: 'light', activeTab: 'Details' } },
      { id: 'dark', name: 'Dark', description: 'Dark themed tabs', args: { orientation: 'horizontal', theme: 'dark', activeTab: 'Overview' } },
    ],
    controls: [
      { key: 'orientation', label: 'Orientation', type: 'select', defaultValue: 'horizontal', options: ['horizontal', 'vertical'] },
      { key: 'theme', label: 'Theme', type: 'select', defaultValue: 'light', options: ['light', 'dark'] },
      { key: 'activeTab', label: 'Active Tab', type: 'select', defaultValue: 'Overview', options: ['Overview', 'Details', 'Resources', 'FAQs'] },
    ],
  },
  {
    slug: 'form-field',
    title: 'Form Field',
    description: 'Accessible form input field supporting text, email, textarea and select types with validation states.',
    status: 'READY',
    ownerTeam: 'Forms Platform',
    aemComponentPath: '/apps/aem-visual-library/components/form/form-field',
    aemLimitations: ['File upload inputs use a separate Upload Field component'],
    stories: [
      { id: 'default', name: 'Text Input', description: 'Standard text input', args: { label: 'Full Name', placeholder: 'Jane Smith', type: 'text', required: false, error: false } },
      { id: 'email', name: 'Email', description: 'Email type input', args: { label: 'Email Address', placeholder: 'you@example.com', type: 'email', required: true, error: false } },
      { id: 'textarea', name: 'Textarea', description: 'Multi-line text area', args: { label: 'Message', placeholder: 'Tell us more…', type: 'textarea', required: false, error: false } },
      { id: 'error', name: 'Error State', description: 'Field with validation error', args: { label: 'Email Address', placeholder: 'you@example.com', type: 'email', required: true, error: true } },
    ],
    controls: [
      { key: 'label', label: 'Label', type: 'text', defaultValue: 'Full Name' },
      { key: 'placeholder', label: 'Placeholder', type: 'text', defaultValue: 'Jane Smith' },
      { key: 'type', label: 'Input Type', type: 'select', defaultValue: 'text', options: ['text', 'email', 'textarea', 'select'] },
      { key: 'required', label: 'Required', type: 'boolean', defaultValue: false },
      { key: 'error', label: 'Show Error', type: 'boolean', defaultValue: false },
    ],
  },
  {
    slug: 'alert',
    title: 'Alert',
    description: 'Inline notification banner for info, success, warning and error messages with optional dismiss.',
    status: 'READY',
    ownerTeam: 'Core Components',
    aemComponentPath: '/apps/aem-visual-library/components/content/alert',
    stories: [
      { id: 'info', name: 'Info', description: 'Informational alert', args: { type: 'info', message: 'This is an informational alert message.', dismissible: true } },
      { id: 'success', name: 'Success', description: 'Success confirmation', args: { type: 'success', message: 'Your changes have been saved successfully.', dismissible: true } },
      { id: 'warning', name: 'Warning', description: 'Warning notification', args: { type: 'warning', message: 'Please review before publishing.', dismissible: true } },
      { id: 'error', name: 'Error', description: 'Error state', args: { type: 'error', message: 'Something went wrong. Please try again.', dismissible: false } },
    ],
    controls: [
      { key: 'type', label: 'Type', type: 'select', defaultValue: 'info', options: ['info', 'success', 'warning', 'error'] },
      { key: 'message', label: 'Message', type: 'text', defaultValue: 'This is an informational alert message.' },
      { key: 'dismissible', label: 'Dismissible', type: 'boolean', defaultValue: true },
    ],
  },
  {
    slug: 'image',
    title: 'Image',
    description: 'Responsive AEM-managed image with lazy loading, alt text, optional caption and configurable aspect ratio.',
    status: 'READY',
    ownerTeam: 'Core Components',
    aemComponentPath: '/apps/aem-visual-library/components/content/image',
    aemLimitations: ['Animated GIFs are not supported', 'Maximum file size: 10 MB'],
    stories: [
      { id: 'default', name: '16:9', description: 'Widescreen ratio', args: { ratio: '16/9', caption: 'An AEM-managed image asset', showCaption: true } },
      { id: 'square', name: '1:1 Square', description: 'Square crop', args: { ratio: '1/1', caption: '', showCaption: false } },
      { id: 'portrait', name: '4:3', description: '4:3 portrait', args: { ratio: '4/3', caption: 'Photo credit: AEM team', showCaption: true } },
    ],
    controls: [
      { key: 'ratio', label: 'Aspect Ratio', type: 'select', defaultValue: '16/9', options: ['16/9', '4/3', '1/1', '3/2'] },
      { key: 'caption', label: 'Caption', type: 'text', defaultValue: 'An AEM-managed image asset' },
      { key: 'showCaption', label: 'Show Caption', type: 'boolean', defaultValue: true },
    ],
  },
  {
    slug: 'video-player',
    title: 'Video Player',
    description: 'Embeddable video component supporting YouTube, Vimeo and self-hosted assets with configurable controls.',
    status: 'IN_REVIEW',
    ownerTeam: 'Media Platform',
    aemComponentPath: '/apps/aem-visual-library/components/content/video-player',
    aemLimitations: [
      'Autoplay is muted-only per browser policy',
      'Self-hosted videos must be uploaded to AEM DAM',
    ],
    stories: [
      { id: 'youtube', name: 'YouTube', description: 'YouTube embed', args: { source: 'youtube', autoplay: false, showControls: true } },
      { id: 'vimeo', name: 'Vimeo', description: 'Vimeo embed', args: { source: 'vimeo', autoplay: false, showControls: true } },
      { id: 'autoplay', name: 'Autoplay', description: 'Muted autoplay', args: { source: 'self-hosted', autoplay: true, showControls: false } },
    ],
    controls: [
      { key: 'source', label: 'Source', type: 'select', defaultValue: 'youtube', options: ['youtube', 'vimeo', 'self-hosted'] },
      { key: 'autoplay', label: 'Autoplay', type: 'boolean', defaultValue: false },
      { key: 'showControls', label: 'Show Controls', type: 'boolean', defaultValue: true },
    ],
  },
  {
    slug: 'teaser',
    title: 'Teaser',
    description: 'Content promotion component combining an image, pre-title, headline and CTA. Multiple visual variants available.',
    status: 'READY',
    ownerTeam: 'Marketing Platform',
    aemComponentPath: '/apps/aem-visual-library/components/content/teaser',
    stories: [
      { id: 'default', name: 'Default', description: 'Standard teaser card', args: { variant: 'default', title: 'Teaser Headline', pretitle: 'FEATURED', showImage: true, theme: 'light' } },
      { id: 'hero', name: 'Hero', description: 'Larger hero teaser', args: { variant: 'hero', title: 'Hero Teaser', pretitle: 'SPOTLIGHT', showImage: true, theme: 'light' } },
      { id: 'promo', name: 'Promo', description: 'Gradient promo style', args: { variant: 'promo', title: 'Special Offer', pretitle: 'LIMITED TIME', showImage: false, theme: 'light' } },
    ],
    controls: [
      { key: 'variant', label: 'Variant', type: 'select', defaultValue: 'default', options: ['default', 'hero', 'promo'] },
      { key: 'title', label: 'Title', type: 'text', defaultValue: 'Teaser Headline' },
      { key: 'pretitle', label: 'Pre-title', type: 'text', defaultValue: 'FEATURED' },
      { key: 'showImage', label: 'Show Image', type: 'boolean', defaultValue: true },
      { key: 'theme', label: 'Theme', type: 'select', defaultValue: 'light', options: ['light', 'dark'] },
    ],
  },
  {
    slug: 'breadcrumb',
    title: 'Breadcrumb',
    description: 'Hierarchical page path navigation automatically derived from the JCR content tree.',
    status: 'READY',
    ownerTeam: 'Core Components',
    aemComponentPath: '/apps/aem-visual-library/components/navigation/breadcrumb',
    aemLimitations: ['Depth is limited to 5 levels'],
    stories: [
      { id: 'default', name: 'Default', description: 'Slash separator', args: { separator: '/', showHome: true, theme: 'light' } },
      { id: 'chevron', name: 'Chevron', description: 'Arrow separator', args: { separator: '›', showHome: true, theme: 'light' } },
      { id: 'dark', name: 'Dark', description: 'Dark background', args: { separator: '/', showHome: true, theme: 'dark' } },
    ],
    controls: [
      { key: 'separator', label: 'Separator', type: 'select', defaultValue: '/', options: ['/', '›', '»', '|'] },
      { key: 'showHome', label: 'Show Home', type: 'boolean', defaultValue: true },
      { key: 'theme', label: 'Theme', type: 'select', defaultValue: 'light', options: ['light', 'dark'] },
    ],
  },
];
