// Mock component data for prototype (no database required)
// This file contains 18 hardcoded AEM components

export interface MockComponent {
  id: string;
  slug: string;
  title: string;
  description: string;
  tags: string[];
  status: 'STABLE' | 'EXPERIMENTAL' | 'DEPRECATED';
  ownerEmail: string;
  ownerTeam: string;
  repoLink?: string;
  azureWikiPath?: string;
  azureWikiUrl?: string;
  figmaLinks: string[];
  aemComponentPath?: string;
  aemDialogSchema?: any;
  aemAllowedChildren?: string[];
  aemTemplateConstraints?: any;
  aemLimitations?: string[];
  thumbnailUrl?: string;
  screenshotAuthorUrl?: string;
  screenshotPublishedUrl?: string;
  lastSyncedAt: Date;
  lastUpdatedBy: string;
  lastUpdatedSource: 'MANUAL' | 'AZURE' | 'GITHUB';
  createdAt: Date;
  updatedAt: Date;
}

export const mockComponents: MockComponent[] = [
  {
    id: '1',
    slug: 'hero-banner',
    title: 'Hero Banner',
    description: 'Large top-of-page banner with background image, headline, subtitle, and up to two CTA buttons. Supports multiple alignment options and overlay styles.',
    tags: ['layout', 'marketing', 'author-editable', 'responsive'],
    status: 'STABLE',
    ownerEmail: 'marketing-platform@example.com',
    ownerTeam: 'Marketing Platform',
    repoLink: 'https://github.com/example/aem-components/tree/main/hero-banner',
    azureWikiPath: '/Components/Hero-Banner',
    azureWikiUrl: 'https://dev.azure.com/example/_wiki/wikis/Components/Hero-Banner',
    figmaLinks: [
      'https://www.figma.com/file/abc123/Design-System?node-id=100-200',
      'https://www.figma.com/file/abc123/Design-System?node-id=100-250',
    ],
    aemComponentPath: '/apps/myproject/components/hero-banner',
    aemDialogSchema: {
      title: { type: 'textfield', required: true },
      subtitle: { type: 'textarea', maxlength: 200 },
      image: { type: 'pathbrowser', rootPath: '/content/dam' },
      ctaPrimaryText: { type: 'textfield', maxlength: 25 },
      ctaPrimaryLink: { type: 'pathfield' },
      ctaSecondaryText: { type: 'textfield', maxlength: 25 },
      ctaSecondaryLink: { type: 'pathfield' },
      alignment: { type: 'select', options: ['left', 'center'] },
      overlay: { type: 'select', options: ['none', 'dark', 'light'] },
    },
    aemAllowedChildren: ['teaser', 'cta-button'],
    aemTemplateConstraints: {
      allowedParents: ['responsivegrid'],
      maxItems: 1,
    },
    aemLimitations: [
      'No video support in authoring dialog',
      'Image ratio fixed to 16:9',
      'Maximum 2 CTA buttons',
    ],
    thumbnailUrl: 'http://localhost:3000/api/placeholder/400x300/2563eb/ffffff?text=Hero+Banner',
    screenshotAuthorUrl: 'http://localhost:3000/api/placeholder/1200x800/1e40af/ffffff?text=Hero+Author+View',
    screenshotPublishedUrl: 'http://localhost:3000/api/placeholder/1200x800/1e3a8a/ffffff?text=Hero+Published',
    lastSyncedAt: new Date('2024-01-01'),
    lastUpdatedBy: 'sarah.designer@example.com',
    lastUpdatedSource: 'AZURE',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    slug: 'cta-button',
    title: 'CTA Button',
    description: 'Call-to-action button component with multiple style variants (primary, secondary, tertiary, ghost) and size options. Supports internal and external links.',
    tags: ['action', 'interactive', 'author-editable', 'atomic'],
    status: 'STABLE',
    ownerEmail: 'design-system@example.com',
    ownerTeam: 'Design System',
    repoLink: 'https://github.com/example/aem-components/tree/main/cta-button',
    azureWikiPath: '/Components/CTA-Button',
    figmaLinks: ['https://www.figma.com/file/abc123/Design-System?node-id=200-300'],
    aemComponentPath: '/apps/myproject/components/cta-button',
    thumbnailUrl: 'http://localhost:3000/api/placeholder/400x300/059669/ffffff?text=CTA+Button',
    screenshotAuthorUrl: 'http://localhost:3000/api/placeholder/1200x800/047857/ffffff?text=Button+Author',
    screenshotPublishedUrl: 'http://localhost:3000/api/placeholder/1200x800/065f46/ffffff?text=Button+Published',
    lastSyncedAt: new Date('2024-01-01'),
    lastUpdatedBy: 'john.developer@example.com',
    lastUpdatedSource: 'AZURE',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '3',
    slug: 'card',
    title: 'Card',
    description: 'Flexible card component for displaying content with optional image, title, description, and CTA. Supports horizontal and vertical layouts with multiple style variants.',
    tags: ['layout', 'content', 'author-editable', 'responsive'],
    status: 'STABLE',
    ownerEmail: 'content-platform@example.com',
    ownerTeam: 'Content Platform',
    repoLink: 'https://github.com/example/aem-components/tree/main/card',
    azureWikiPath: '/Components/Card',
    figmaLinks: [
      'https://www.figma.com/file/abc123/Design-System?node-id=300-400',
      'https://www.figma.com/file/abc123/Design-System?node-id=300-450',
    ],
    aemComponentPath: '/apps/myproject/components/card',
    thumbnailUrl: 'http://localhost:3000/api/placeholder/400x300/dc2626/ffffff?text=Card',
    screenshotAuthorUrl: 'http://localhost:3000/api/placeholder/1200x800/b91c1c/ffffff?text=Card+Author',
    screenshotPublishedUrl: 'http://localhost:3000/api/placeholder/1200x800/991b1b/ffffff?text=Card+Published',
    lastSyncedAt: new Date('2024-01-01'),
    lastUpdatedBy: 'sarah.designer@example.com',
    lastUpdatedSource: 'AZURE',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '4',
    slug: 'navigation-header',
    title: 'Navigation Header',
    description: 'Main site navigation header with logo, primary navigation menu, search, and user actions. Includes responsive mobile menu with hamburger toggle.',
    tags: ['navigation', 'layout', 'global', 'responsive'],
    status: 'STABLE',
    ownerEmail: 'platform-team@example.com',
    ownerTeam: 'Platform',
    repoLink: 'https://github.com/example/aem-components/tree/main/navigation-header',
    azureWikiPath: '/Components/Navigation-Header',
    figmaLinks: ['https://www.figma.com/file/abc123/Design-System?node-id=400-500'],
    aemComponentPath: '/apps/myproject/components/navigation-header',
    thumbnailUrl: 'http://localhost:3000/api/placeholder/400x300/7c3aed/ffffff?text=Navigation',
    screenshotAuthorUrl: 'http://localhost:3000/api/placeholder/1200x800/6d28d9/ffffff?text=Nav+Author',
    screenshotPublishedUrl: 'http://localhost:3000/api/placeholder/1200x800/5b21b6/ffffff?text=Nav+Published',
    lastSyncedAt: new Date('2024-01-01'),
    lastUpdatedBy: 'platform@example.com',
    lastUpdatedSource: 'AZURE',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '5',
    slug: 'accordion',
    title: 'Accordion',
    description: 'Expandable/collapsible content sections. Supports single or multiple open panels, with optional icons and custom styling.',
    tags: ['interactive', 'content', 'author-editable', 'accessible'],
    status: 'STABLE',
    ownerEmail: 'content-platform@example.com',
    ownerTeam: 'Content Platform',
    repoLink: 'https://github.com/example/aem-components/tree/main/accordion',
    azureWikiPath: '/Components/Accordion',
    figmaLinks: ['https://www.figma.com/file/abc123/Design-System?node-id=500-600'],
    aemComponentPath: '/apps/myproject/components/accordion',
    thumbnailUrl: 'http://localhost:3000/api/placeholder/400x300/ea580c/ffffff?text=Accordion',
    screenshotAuthorUrl: 'http://localhost:3000/api/placeholder/1200x800/c2410c/ffffff?text=Accordion+Author',
    screenshotPublishedUrl: 'http://localhost:3000/api/placeholder/1200x800/9a3412/ffffff?text=Accordion+Published',
    lastSyncedAt: new Date('2024-01-01'),
    lastUpdatedBy: 'john.developer@example.com',
    lastUpdatedSource: 'AZURE',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '6',
    slug: 'tabs',
    title: 'Tabs',
    description: 'Tabbed content container for organizing related information. Supports horizontal and vertical tab orientations with keyboard navigation.',
    tags: ['interactive', 'content', 'author-editable', 'accessible'],
    status: 'STABLE',
    ownerEmail: 'content-platform@example.com',
    ownerTeam: 'Content Platform',
    repoLink: 'https://github.com/example/aem-components/tree/main/tabs',
    azureWikiPath: '/Components/Tabs',
    figmaLinks: ['https://www.figma.com/file/abc123/Design-System?node-id=600-700'],
    aemComponentPath: '/apps/myproject/components/tabs',
    thumbnailUrl: 'http://localhost:3000/api/placeholder/400x300/0891b2/ffffff?text=Tabs',
    screenshotAuthorUrl: 'http://localhost:3000/api/placeholder/1200x800/0e7490/ffffff?text=Tabs+Author',
    screenshotPublishedUrl: 'http://localhost:3000/api/placeholder/1200x800/155e75/ffffff?text=Tabs+Published',
    lastSyncedAt: new Date('2024-01-01'),
    lastUpdatedBy: 'sarah.designer@example.com',
    lastUpdatedSource: 'AZURE',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '7',
    slug: 'form-field',
    title: 'Form Field',
    description: 'Flexible form input component supporting text, email, tel, number, textarea, select, checkbox, and radio inputs. Includes validation and error messaging.',
    tags: ['form', 'interactive', 'author-editable', 'accessible'],
    status: 'STABLE',
    ownerEmail: 'forms-team@example.com',
    ownerTeam: 'Forms',
    repoLink: 'https://github.com/example/aem-components/tree/main/form-field',
    azureWikiPath: '/Components/Form-Field',
    figmaLinks: ['https://www.figma.com/file/abc123/Design-System?node-id=700-800'],
    aemComponentPath: '/apps/myproject/components/form-field',
    thumbnailUrl: 'http://localhost:3000/api/placeholder/400x300/65a30d/ffffff?text=Form+Field',
    screenshotAuthorUrl: 'http://localhost:3000/api/placeholder/1200x800/4d7c0f/ffffff?text=Form+Author',
    screenshotPublishedUrl: 'http://localhost:3000/api/placeholder/1200x800/3f6212/ffffff?text=Form+Published',
    lastSyncedAt: new Date('2024-01-01'),
    lastUpdatedBy: 'forms@example.com',
    lastUpdatedSource: 'AZURE',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '8',
    slug: 'image',
    title: 'Image',
    description: 'Responsive image component with lazy loading, multiple crop ratios, and caption support. Integrates with AEM DAM for asset management.',
    tags: ['media', 'author-editable', 'responsive', 'atomic'],
    status: 'STABLE',
    ownerEmail: 'design-system@example.com',
    ownerTeam: 'Design System',
    repoLink: 'https://github.com/example/aem-components/tree/main/image',
    azureWikiPath: '/Components/Image',
    figmaLinks: ['https://www.figma.com/file/abc123/Design-System?node-id=800-900'],
    aemComponentPath: '/apps/myproject/components/image',
    thumbnailUrl: 'http://localhost:3000/api/placeholder/400x300/ec4899/ffffff?text=Image',
    screenshotAuthorUrl: 'http://localhost:3000/api/placeholder/1200x800/db2777/ffffff?text=Image+Author',
    screenshotPublishedUrl: 'http://localhost:3000/api/placeholder/1200x800/be185d/ffffff?text=Image+Published',
    lastSyncedAt: new Date('2024-01-01'),
    lastUpdatedBy: 'sarah.designer@example.com',
    lastUpdatedSource: 'AZURE',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '9',
    slug: 'video-player',
    title: 'Video Player',
    description: 'HTML5 video player with controls, captions, and thumbnail preview. Supports YouTube, Vimeo, and self-hosted videos.',
    tags: ['media', 'interactive', 'author-editable', 'accessible'],
    status: 'STABLE',
    ownerEmail: 'media-team@example.com',
    ownerTeam: 'Media',
    repoLink: 'https://github.com/example/aem-components/tree/main/video-player',
    azureWikiPath: '/Components/Video-Player',
    figmaLinks: ['https://www.figma.com/file/abc123/Design-System?node-id=900-1000'],
    aemComponentPath: '/apps/myproject/components/video-player',
    thumbnailUrl: 'http://localhost:3000/api/placeholder/400x300/8b5cf6/ffffff?text=Video+Player',
    screenshotAuthorUrl: 'http://localhost:3000/api/placeholder/1200x800/7c3aed/ffffff?text=Video+Author',
    screenshotPublishedUrl: 'http://localhost:3000/api/placeholder/1200x800/6d28d9/ffffff?text=Video+Published',
    lastSyncedAt: new Date('2024-01-01'),
    lastUpdatedBy: 'media@example.com',
    lastUpdatedSource: 'AZURE',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '10',
    slug: 'breadcrumb',
    title: 'Breadcrumb',
    description: 'Navigational breadcrumb trail showing page hierarchy. Auto-generates from page structure with customization options.',
    tags: ['navigation', 'seo', 'accessible', 'responsive'],
    status: 'STABLE',
    ownerEmail: 'platform-team@example.com',
    ownerTeam: 'Platform',
    repoLink: 'https://github.com/example/aem-components/tree/main/breadcrumb',
    azureWikiPath: '/Components/Breadcrumb',
    figmaLinks: ['https://www.figma.com/file/abc123/Design-System?node-id=1000-1100'],
    aemComponentPath: '/apps/myproject/components/breadcrumb',
    thumbnailUrl: 'http://localhost:3000/api/placeholder/400x300/14b8a6/ffffff?text=Breadcrumb',
    screenshotAuthorUrl: 'http://localhost:3000/api/placeholder/1200x800/0d9488/ffffff?text=Breadcrumb+Author',
    screenshotPublishedUrl: 'http://localhost:3000/api/placeholder/1200x800/0f766e/ffffff?text=Breadcrumb+Published',
    lastSyncedAt: new Date('2024-01-01'),
    lastUpdatedBy: 'platform@example.com',
    lastUpdatedSource: 'AZURE',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '11',
    slug: 'footer',
    title: 'Footer',
    description: 'Site-wide footer with multiple column layouts, social links, copyright, and legal links. Supports newsletter signup integration.',
    tags: ['layout', 'global', 'navigation', 'responsive'],
    status: 'STABLE',
    ownerEmail: 'platform-team@example.com',
    ownerTeam: 'Platform',
    repoLink: 'https://github.com/example/aem-components/tree/main/footer',
    azureWikiPath: '/Components/Footer',
    figmaLinks: ['https://www.figma.com/file/abc123/Design-System?node-id=1100-1200'],
    aemComponentPath: '/apps/myproject/components/footer',
    thumbnailUrl: 'http://localhost:3000/api/placeholder/400x300/6366f1/ffffff?text=Footer',
    screenshotAuthorUrl: 'http://localhost:3000/api/placeholder/1200x800/4f46e5/ffffff?text=Footer+Author',
    screenshotPublishedUrl: 'http://localhost:3000/api/placeholder/1200x800/4338ca/ffffff?text=Footer+Published',
    lastSyncedAt: new Date('2024-01-01'),
    lastUpdatedBy: 'platform@example.com',
    lastUpdatedSource: 'AZURE',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '12',
    slug: 'text-block',
    title: 'Text Block',
    description: 'Rich text editor component for formatted content. Supports headings, lists, links, inline images, and custom styles.',
    tags: ['content', 'text', 'author-editable', 'rich-text'],
    status: 'STABLE',
    ownerEmail: 'content-platform@example.com',
    ownerTeam: 'Content Platform',
    repoLink: 'https://github.com/example/aem-components/tree/main/text-block',
    azureWikiPath: '/Components/Text-Block',
    figmaLinks: ['https://www.figma.com/file/abc123/Design-System?node-id=1200-1300'],
    aemComponentPath: '/apps/myproject/components/text-block',
    thumbnailUrl: 'http://localhost:3000/api/placeholder/400x300/64748b/ffffff?text=Text+Block',
    screenshotAuthorUrl: 'http://localhost:3000/api/placeholder/1200x800/475569/ffffff?text=Text+Author',
    screenshotPublishedUrl: 'http://localhost:3000/api/placeholder/1200x800/334155/ffffff?text=Text+Published',
    lastSyncedAt: new Date('2024-01-01'),
    lastUpdatedBy: 'john.developer@example.com',
    lastUpdatedSource: 'AZURE',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '13',
    slug: 'carousel',
    title: 'Carousel',
    description: 'Image or content carousel with auto-play, navigation arrows, and pagination dots. Supports swipe gestures on touch devices.',
    tags: ['interactive', 'media', 'author-editable', 'responsive'],
    status: 'EXPERIMENTAL',
    ownerEmail: 'ux-team@example.com',
    ownerTeam: 'UX',
    repoLink: 'https://github.com/example/aem-components/tree/main/carousel',
    azureWikiPath: '/Components/Carousel',
    figmaLinks: ['https://www.figma.com/file/abc123/Design-System?node-id=1300-1400'],
    aemComponentPath: '/apps/myproject/components/carousel',
    thumbnailUrl: 'http://localhost:3000/api/placeholder/400x300/f59e0b/ffffff?text=Carousel',
    screenshotAuthorUrl: 'http://localhost:3000/api/placeholder/1200x800/d97706/ffffff?text=Carousel+Author',
    screenshotPublishedUrl: 'http://localhost:3000/api/placeholder/1200x800/b45309/ffffff?text=Carousel+Published',
    lastSyncedAt: new Date('2024-01-01'),
    lastUpdatedBy: 'ux@example.com',
    lastUpdatedSource: 'MANUAL',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '14',
    slug: 'modal',
    title: 'Modal',
    description: 'Modal dialog component for displaying overlaying content. Supports custom sizes, close behaviors, and accessibility features.',
    tags: ['interactive', 'overlay', 'accessible', 'author-editable'],
    status: 'STABLE',
    ownerEmail: 'ux-team@example.com',
    ownerTeam: 'UX',
    repoLink: 'https://github.com/example/aem-components/tree/main/modal',
    azureWikiPath: '/Components/Modal',
    figmaLinks: ['https://www.figma.com/file/abc123/Design-System?node-id=1400-1500'],
    aemComponentPath: '/apps/myproject/components/modal',
    thumbnailUrl: 'http://localhost:3000/api/placeholder/400x300/06b6d4/ffffff?text=Modal',
    screenshotAuthorUrl: 'http://localhost:3000/api/placeholder/1200x800/0891b2/ffffff?text=Modal+Author',
    screenshotPublishedUrl: 'http://localhost:3000/api/placeholder/1200x800/0e7490/ffffff?text=Modal+Published',
    lastSyncedAt: new Date('2024-01-01'),
    lastUpdatedBy: 'ux@example.com',
    lastUpdatedSource: 'AZURE',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '15',
    slug: 'alert',
    title: 'Alert',
    description: 'Alert banner for displaying informational, success, warning, or error messages. Supports dismissible and persistent variants.',
    tags: ['notification', 'feedback', 'author-editable', 'accessible'],
    status: 'STABLE',
    ownerEmail: 'design-system@example.com',
    ownerTeam: 'Design System',
    repoLink: 'https://github.com/example/aem-components/tree/main/alert',
    azureWikiPath: '/Components/Alert',
    figmaLinks: ['https://www.figma.com/file/abc123/Design-System?node-id=1500-1600'],
    aemComponentPath: '/apps/myproject/components/alert',
    thumbnailUrl: 'http://localhost:3000/api/placeholder/400x300/10b981/ffffff?text=Alert',
    screenshotAuthorUrl: 'http://localhost:3000/api/placeholder/1200x800/059669/ffffff?text=Alert+Author',
    screenshotPublishedUrl: 'http://localhost:3000/api/placeholder/1200x800/047857/ffffff?text=Alert+Published',
    lastSyncedAt: new Date('2024-01-01'),
    lastUpdatedBy: 'sarah.designer@example.com',
    lastUpdatedSource: 'AZURE',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '16',
    slug: 'teaser',
    title: 'Teaser',
    description: 'Versatile content promotion component combining image, pre-title, title, description, and action links. Supports multiple rendering variants (default, hero, promo, card) with extensive customization options for enterprise content strategies.',
    tags: ['content', 'marketing', 'promotion', 'core-component', 'responsive', 'author-editable'],
    status: 'STABLE',
    ownerEmail: 'creative-dev@example.com',
    ownerTeam: 'Creative Development',
    repoLink: 'https://github.com/example/aem-core-components/tree/main/teaser',
    azureWikiPath: '/Components/Advanced/Teaser',
    azureWikiUrl: 'https://dev.azure.com/example/_wiki/wikis/Components/Advanced/Teaser',
    figmaLinks: [
      'https://www.figma.com/file/abc123/AEM-Core-Components?node-id=1600-2000',
      'https://www.figma.com/file/abc123/AEM-Core-Components?node-id=1600-2100',
      'https://www.figma.com/file/abc123/AEM-Core-Components?node-id=1600-2200',
    ],
    aemComponentPath: '/apps/core/wcm/components/teaser/v2/teaser',
    thumbnailUrl: 'http://localhost:3000/api/placeholder/400x300/8b5cf6/ffffff?text=Teaser',
    screenshotAuthorUrl: 'http://localhost:3000/api/placeholder/1200x800/7c3aed/ffffff?text=Teaser+Author',
    screenshotPublishedUrl: 'http://localhost:3000/api/placeholder/1200x800/6d28d9/ffffff?text=Teaser+Published',
    lastSyncedAt: new Date('2024-01-01'),
    lastUpdatedBy: 'creative-dev@example.com',
    lastUpdatedSource: 'MANUAL',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '17',
    slug: 'section-container',
    title: 'Section Container',
    description: 'Advanced layout container with extensive styling options including background (color, image, video), spacing controls, grid configurations, and overlay effects. Designed for enterprise page composition with maximum flexibility.',
    tags: ['layout', 'container', 'structure', 'responsive', 'grid', 'author-editable'],
    status: 'STABLE',
    ownerEmail: 'creative-dev@example.com',
    ownerTeam: 'Creative Development',
    repoLink: 'https://github.com/example/aem-core-components/tree/main/section-container',
    azureWikiPath: '/Components/Advanced/Section-Container',
    azureWikiUrl: 'https://dev.azure.com/example/_wiki/wikis/Components/Advanced/Section-Container',
    figmaLinks: [
      'https://www.figma.com/file/abc123/AEM-Core-Components?node-id=2000-2500',
      'https://www.figma.com/file/abc123/AEM-Core-Components?node-id=2000-2600',
    ],
    aemComponentPath: '/apps/core/wcm/components/container/v2/container',
    thumbnailUrl: 'http://localhost:3000/api/placeholder/400x300/3b82f6/ffffff?text=Section+Container',
    screenshotAuthorUrl: 'http://localhost:3000/api/placeholder/1200x800/2563eb/ffffff?text=Container+Author',
    screenshotPublishedUrl: 'http://localhost:3000/api/placeholder/1200x800/1d4ed8/ffffff?text=Container+Published',
    lastSyncedAt: new Date('2024-01-01'),
    lastUpdatedBy: 'creative-dev@example.com',
    lastUpdatedSource: 'MANUAL',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '18',
    slug: 'content-list',
    title: 'Content List',
    description: 'Intelligent list component with multiple data source options (child pages, tag-based queries, static items, search results). Features dynamic rendering, pagination, filtering, and extensive display customization for content aggregation and curation.',
    tags: ['content', 'dynamic', 'query', 'list', 'aggregation', 'author-editable'],
    status: 'STABLE',
    ownerEmail: 'creative-dev@example.com',
    ownerTeam: 'Creative Development',
    repoLink: 'https://github.com/example/aem-core-components/tree/main/content-list',
    azureWikiPath: '/Components/Advanced/Content-List',
    azureWikiUrl: 'https://dev.azure.com/example/_wiki/wikis/Components/Advanced/Content-List',
    figmaLinks: [
      'https://www.figma.com/file/abc123/AEM-Core-Components?node-id=2500-3000',
    ],
    aemComponentPath: '/apps/core/wcm/components/list/v4/list',
    thumbnailUrl: 'http://localhost:3000/api/placeholder/400x300/10b981/ffffff?text=Content+List',
    screenshotAuthorUrl: 'http://localhost:3000/api/placeholder/1200x800/059669/ffffff?text=List+Author',
    screenshotPublishedUrl: 'http://localhost:3000/api/placeholder/1200x800/047857/ffffff?text=List+Published',
    lastSyncedAt: new Date('2024-01-01'),
    lastUpdatedBy: 'creative-dev@example.com',
    lastUpdatedSource: 'MANUAL',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];
